### ISSUE TITLE
Needing mutliple copies

### ISSUE THREAD

**Issue by SyalFett** [ThreeAmigosModding/TAM_BetterRadioAnims#2]
if i see this config right you set the drawable once wich right now is 9 so the vest but the earpiece usually is a mask and there is also a radio, when using eup, within the parachutes.
so one needs at least 3 copies to get it all.

also is there a way to disable the some like the earpiece animation if one dont want it maybe?

**Comment by HakkoDev** [comment]
To clarify you mean you want different drawables per animation yes?

**Comment by HakkoDev** [comment]
Like so: 
![image](https://github.com/ThreeAmigosModding/TAM_BetterRadioAnims/assets/67168651/d0d9e74f-2c78-4628-919c-83b605714733)

**Comment by HakkoDev** [comment]
solved in latest commit
