### ISSUE TITLE
attempt to index a nil value (global 'config')

### ISSUE THREAD

**Issue by JeyCraft** [ThreeAmigosModding/TAM_BetterRadioAnims#5]
Got this Issue maybe u can Help 

[script:TAM_BetterRad] [TAM_BetterRadioAnims] [INFO] Successfully loaded scully_emotemenu integration!
[script:TAM_BetterRad] [TAM_BetterRadioAnims] [INFO] Join our Discord for support: discord.gg/threeamigos
[script:TAM_BetterRad] [TAM_BetterRadioAnims] [INFO] Documentation: docs.threeamigos.shop
[script:TAM_BetterRad] SCRIPT ERROR: @TAM_BetterRadioAnims/server/main.lua:32: attempt to index a nil value (global 'config')

**Comment by HakkoDev** [comment]
download release not source
